Implements API
milealmeida/side-project-coinswap pull request #14
Opened 2023-08-08 00:01 UTC by iamdevmarcos

2023-08-08 13:13 UTC, milealmeida commented on src/assets/img/index.ts
> +import defaultFlag from './default.svg';
Apaga essa importação já que não vamos ter mais o default.

2023-08-08 13:22 UTC, milealmeida commented on src/utils/content.ts
> +    id: 7,
Remover esse default

2023-08-08 13:35 UTC, milealmeida commented on src/App.tsx
> +import { CurrencyProvider } from 'contexts/currency.tsx';
remove o .tsx

2023-08-08 13:35 UTC, milealmeida commented on src/components/Input.tsx
> +      defaultFlag: country[6]
remover a defaultFlag

2023-08-08 13:36 UTC, milealmeida commented on src/components/Input.tsx
> +    return countries[currencyKey] ?? countries.defaultFlag;
a default pode ser a bandeira do EUA

2023-08-08 13:38 UTC, milealmeida commented on src/components/Input.tsx
> +            .filter((item) => item.code !== 'default')
se não vai ter default, creio que não precisa do filter

2023-08-08 13:39 UTC, milealmeida commented on src/services/queries.ts
> +export const GET_CURRENCY_VALUE = async ({
Renomeia essa variável, não estamos no java aqui >.<

2023-08-08 13:41 UTC, milealmeida commented on src/contexts/currency.tsx
> +  const onSuccess = async (response: AxiosResponse) => {
Chama do data direto

2023-08-08 13:44 UTC, milealmeida requested changes
Só perfumaria, hj estou de bom humor  :)

2023-08-08 22:33 UTC, iamdevmarcos commented on src/App.tsx
> +import { CurrencyProvider } from 'contexts/currency.tsx';
é necessario ter o .tsx pois o `children` do CurrencyProvider é um React Element.

2023-08-08 22:53 UTC, iamdevmarcos commented on src/contexts/currency.tsx
> +  const onSuccess = async (response: AxiosResponse) => {
Ok, chamei direto, mas como a chave de retorno da API sempre muda, precisei criar um type generic na Tipagem desse onSuccess.

2023-08-09 17:32 UTC, milealmeida approved these changes

2023-08-09 17:37 UTC, merged