Implements Initial Config to Project
milealmeida/side-project-coinswap pull request #3
Opened 2023-06-16 18:47 UTC by iamdevmarcos

2023-06-16 20:34 UTC, milealmeida requested changes

2023-06-16 20:34 UTC, milealmeida commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
Aqui não vai tirar a formatação quando salvar??

2023-06-16 20:34 UTC, milealmeida commented on src/App.tsx
> +import { Home } from 'pages'
Colocar a configuração de ; no eslint por favor

2023-06-17 09:04 UTC, iamdevmarcos commented on .vscode/settings.json
> +  "editor.formatOnSave": false,
Isso é para o Eslint funcionar.
Eu digo pro VSCODE que a responsabilidade de salvar o codigo nao é dele, e sim do Eslint.

2023-06-17 09:04 UTC, iamdevmarcos commented on src/App.tsx
> +import { Home } from 'pages'
Vamos usar `;`?

2023-06-17 11:57 UTC, milealmeida commented on src/App.tsx
> +import { Home } from 'pages'
Positivo

2023-06-18 09:39 UTC, iamdevmarcos commented on src/App.tsx
> +import { Home } from 'pages'
Resolvido.

2023-06-18 12:28 UTC, milealmeida approved these changes

2023-06-18 12:29 UTC, merged