Implements recharts
milealmeida/side-project-coinswap pull request #8
Opened 2023-06-26 23:19 UTC by iamdevmarcos

2023-06-26 23:30 UTC, milealmeida requested changes

2023-06-26 23:30 UTC, milealmeida commented on src/components/Chart.tsx
> +  return (
Tira o return

2023-06-26 23:30 UTC, milealmeida commented on src/pages/Home.tsx
> +import { useEffect, useState } from 'react';
Coloca na linha 1

2023-06-28 21:27 UTC, iamdevmarcos commented on src/components/Chart.tsx
> +  return (
Feito

2023-06-28 21:28 UTC, iamdevmarcos commented on src/pages/Home.tsx
> +import { useEffect, useState } from 'react';
Feito

2023-06-29 14:49 UTC, milealmeida approved these changes

2023-06-29 14:50 UTC, merged